Arearange
cawasser/vanilla pull request #45
Opened 2020-02-26 23:32 UTC by neeldave

2020-02-27 01:39 UTC, bfhub reviewed
the updated vanilla-db is missing.

2020-02-27 01:55 UTC, bfhub approved these changes
please ignore my last comment, no updated vanilla-db is needed.

2020-02-27 18:35 UTC, gpierce3 requested changes
Pulled latest and ran.
Hit the Add button to launch widget modal.
Scroll down and select AreaRange Data from the service list.
No widget png file shows for me to select.
Unable to display widget.

Looked thru the code and don't see anything that looks out of whack.
Not sure if I've missed something.

2020-02-27 18:45 UTC, bfhub reviewed
@gpierce3 make sure you update the vanilla-db, Neel has added a new service.

2020-02-27 19:43 UTC, gpierce3 approved these changes

2020-02-27 20:36 UTC, cawasser commented on docs/adding-new-widget-types.md
> +
Add a note that it is very important do get the "names' to match between in the service table and in service-def, and that the :data-format(s) need to match between the services table and widget-defs so you can add new services/widgets to the UI

2020-02-27 20:37 UTC, cawasser commented on src/clj/vanilla/db/core.clj
> +  (initialize-database vanilla-default)
the data above if correct, but vanilla_default hasn't been updated to refrlect the change to "date-yl-yh"

2020-02-27 20:39 UTC, cawasser requested changes
need to get an up-to-date vanilla_default into the repo

2020-02-28 18:40 UTC, bfhub approved these changes
deleted the vanilla-db, pulled the recent changes, and ran "lian run", and "lein figwheel". a new vanilla-db was created. verified the arearrange widget.

2020-02-28 21:26 UTC, gpierce3 commented
Pulled latest.
Deleted vanilla db
ran lein run
New vanilla db created
ran lein figwheel
launched web browser
Was able to select Arearange data service and arearange widget
Widget displayed on screen.

Looks good.

2020-03-04 22:28 UTC, cawasser approved these changes

2020-03-05 17:53 UTC, merged